#! /bin/bash

readonly BASEDIR="$(dirname $(readlink -f "$0"))"
readonly BASEURL="http://www.sonatype.org/downloads"
readonly BINARY="nexus-2.7.0-bundle.tar.gz"

set -e
mkdir -p "${BASEDIR}/SOURCES/"
cd "${BASEDIR}/SOURCES/"
wget "${BASEURL}/${BINARY}"
